/* Single source of truth for the /networks map. The bulk dataset lives in
 * companies.json (generated by experiments/networks/build_network.py from the
 * research swarm); this module types it, validates it at build time, and
 * re-exports. The client script imports the same module, so server and client
 * can never drift — mirrors the src/data/team.ts pattern.
 *
 * The private overlay (warm paths + pipeline stage) is NOT imported here — it
 * is read from private/overlay.json in NetworkGraph.astro, dev-only. */

import raw from "./companies.json";
import type { Company, CompanyEdge, NetworkData, SubcategoryTable } from "./network-types";
import { VERTICALS } from "./network-types";

export * from "./network-types";

const data = raw as NetworkData;
export const companies: Company[] = data.companies;
export const edges: CompanyEdge[] = data.edges;
export const meta = data.meta ?? {};
/* Ordered "what they do" sub-categories per vertical — drives the directory. */
export const subcategories: SubcategoryTable =
  (meta as { subcategories?: SubcategoryTable }).subcategories ?? ({} as SubcategoryTable);

/* Fail at build time, not in front of a customer. */
const verticalIds = new Set(VERTICALS.map((v) => v.id));
const ids = new Set<string>();
for (const c of companies) {
  if (ids.has(c.id)) throw new Error(`companies.json: duplicate id "${c.id}"`);
  ids.add(c.id);
  if (!verticalIds.has(c.vertical)) throw new Error(`companies.json: "${c.id}" has unknown vertical "${c.vertical}"`);
  if (typeof c.intensity !== "number" || c.intensity < 0 || c.intensity > 5)
    throw new Error(`companies.json: "${c.id}" intensity ${c.intensity} out of range 0..5`);
  const subs = subcategories[c.vertical];
  if (!subs?.some((s) => s.key === c.subcategory))
    throw new Error(`companies.json: "${c.id}" subcategory "${c.subcategory}" not in ${c.vertical} taxonomy`);
  if (typeof c.priorityRank !== "number")
    throw new Error(`companies.json: "${c.id}" missing numeric priorityRank`);
}
for (const e of edges) {
  if (!ids.has(e.source)) throw new Error(`companies.json: edge from unknown company "${e.source}"`);
  if (!ids.has(e.target)) throw new Error(`companies.json: edge to unknown company "${e.target}"`);
  if (e.source === e.target) throw new Error(`companies.json: self-loop on "${e.source}"`);
}
